import type { BusRoute } from './types';
import type { Booking } from '@/lib/types';

export const mockBusRoutes: BusRoute[] = [
  {
    id: '1',
    operator: 'Hanif Enterprise',
    from: 'Dhaka',
    to: 'Chittagong',
    class: 'ac-seater',
    departureTime: '08:00 AM',
    arrivalTime: '04:00 PM',
    duration: '8h',
    price: 750,
    rating: 4.5,
    amenities: ['AC', 'WiFi', 'Charging Port'],
    seatLayout: {
      rows: [
        ['A1', 'A2', '', 'A3', 'A4'],
        ['B1', 'B2', '', 'B3', 'B4'],
        ['C1', 'C2', '', 'C3', 'C4'],
        ['D1', 'D2', '', 'D3', 'D4'],
        ['E1', 'E2', '', 'E3', 'E4'],
        ['F1', 'F2', '', 'F3', 'F4'],
        ['G1', 'G2', '', 'G3', 'G4'],
        ['H1', 'H2', '', 'H3', 'H4'],
      ],
      booked: ['A2', 'C3', 'C4', 'F1', 'G3'],
    },
    pickupPoints: [
      { name: 'Gabtoli', time: '07:30 AM' },
      { name: 'Mohakhali', time: '08:00 AM' },
      { name: 'Abdullahpur', time: '08:30 AM' },
    ],
  },
  {
    id: '2',
    operator: 'Shyamoli NR Travels',
    from: 'Dhaka',
    to: 'Chittagong',
    class: 'business-ac',
    departureTime: '10:30 PM',
    arrivalTime: '06:30 AM',
    duration: '8h',
    price: 1200,
    rating: 4.8,
    amenities: ['AC', 'WiFi', 'Blanket', 'Water Bottle'],
    seatLayout: {
      rows: [
        ['A1', 'A2', '', 'A3', 'A4'],
        ['B1', 'B2', '', 'B3', 'B4'],
        ['C1', 'C2', '', 'C3', 'C4'],
        ['D1', 'D2', '', 'D3', 'D4'],
        ['E1', 'E2', '', 'E3', 'E4'],
        ['F1', 'F2', '', 'F3', 'F4'],
        ['G1', 'G2', '', 'G3', 'G4'],
        ['H1', 'H2', '', 'H3', 'H4'],
      ],
      booked: ['B1', 'B2', 'D4', 'E2', 'H1', 'H2', 'H4'],
    },
    pickupPoints: [
      { name: 'Kollanpur', time: '10:00 PM' },
      { name: 'Arambagh', time: '10:30 PM' },
    ],
  },
  {
    id: '3',
    operator: 'Green Line Paribahan',
    from: 'Dhaka',
    to: 'Sylhet',
    class: 'business-ac',
    departureTime: '07:00 AM',
    arrivalTime: '01:00 PM',
    duration: '6h',
    price: 1000,
    rating: 4.7,
    amenities: ['AC', 'WiFi', 'Snacks'],
    seatLayout: {
      rows: [
        ['A1', 'A2', '', 'A3', 'A4'],
        ['B1', 'B2', '', 'B3', 'B4'],
        ['C1', 'C2', '', 'C3', 'C4'],
        ['D1', 'D2', '', 'D3', 'D4'],
        ['E1', 'E2', '', 'E3', 'E4'],
        ['F1', 'F2', '', 'F3', 'F4'],
      ],
      booked: ['A1', 'A4', 'C2', 'D3'],
    },
    pickupPoints: [
      { name: 'Gabtoli', time: '06:30 AM' },
      { name: 'Mohakhali', time: '07:00 AM' },
    ],
  },
  {
    id: '4',
    operator: 'Ena Transport (Pvt) Ltd',
    from: 'Sylhet',
    to: 'Dhaka',
    class: 'non-ac',
    departureTime: '02:00 PM',
    arrivalTime: '08:30 PM',
    duration: '6h 30m',
    price: 600,
    rating: 4.2,
    amenities: ['WiFi'],
    seatLayout: {
      rows: [
        ['A1', 'A2', '', 'A3', 'A4'],
        ['B1', 'B2', '', 'B3', 'B4'],
        ['C1', 'C2', '', 'C3', 'C4'],
        ['D1', 'D2', '', 'D3', 'D4'],
        ['E1', 'E2', '', 'E3', 'E4'],
        ['F1', 'F2', '', 'F3', 'F4'],
        ['G1', 'G2', '', 'G3', 'G4'],
      ],
      booked: ['B3', 'C1', 'C2', 'E4', 'F2', 'G1'],
    },
    pickupPoints: [
      { name: 'Kadamtali Bus Stand', time: '01:30 PM' },
      { name: 'Sobhani Ghat', time: '02:00 PM' },
    ],
  },
  {
    id: '5',
    operator: 'Shohagh Paribahan',
    from: 'Dhaka',
    to: 'Khulna',
    class: 'sleeper-ac',
    departureTime: '09:00 PM',
    arrivalTime: '05:00 AM',
    duration: '8h',
    price: 800,
    rating: 4.4,
    amenities: ['AC', 'WiFi', 'Water Bottle'],
    seatLayout: {
      rows: [
        ['A1', 'A2', '', 'A3', 'A4'],
        ['B1', 'B2', '', 'B3', 'B4'],
        ['C1', 'C2', '', 'C3', 'C4'],
        ['D1', 'D2', '', 'D3', 'D4'],
        ['E1', 'E2', '', 'E3', 'E4'],
        ['F1', 'F2', '', 'F3', 'F4'],
        ['G1', 'G2', '', 'G3', 'G4'],
        ['H1', 'H2', '', 'H3', 'H4'],
      ],
      booked: ['A3', 'B1', 'D2', 'D3', 'E1', 'G4', 'H2'],
    },
    pickupPoints: [
      { name: 'Gabtoli', time: '08:30 PM' },
      { name: 'Savar', time: '09:00 PM' },
    ],
  },
  {
    id: '6',
    operator: 'Shyamoli NR Travels',
    from: 'Dhaka',
    to: 'Chittagong',
    class: 'non-ac',
    departureTime: '09:00 AM',
    arrivalTime: '05:00 PM',
    duration: '8h',
    price: 550,
    rating: 4.1,
    amenities: [],
    seatLayout: {
      rows: [
        ['A1', 'A2', '', 'A3', 'A4'],
        ['B1', 'B2', '', 'B3', 'B4'],
        ['C1', 'C2', '', 'C3', 'C4'],
        ['D1', 'D2', '', 'D3', 'D4'],
        ['E1', 'E2', '', 'E3', 'E4'],
        ['F1', 'F2', '', 'F3', 'F4'],
        ['G1', 'G2', '', 'G3', 'G4'],
        ['H1', 'H2', '', 'H3', 'H4'],
      ],
      booked: ['A1', 'C1', 'C2', 'F4', 'G2'],
    },
    pickupPoints: [
      { name: 'Kollanpur', time: '08:30 AM' },
      { name: 'Arambagh', time: '09:00 AM' },
    ],
  },
];


const futureDate = (days: number) => {
    const date = new Date();
    date.setDate(date.getDate() + days);
    return date.toISOString();
}

export const mockBookings: Booking[] = [
  {
    pnr: 'SY123456',
    status: 'Paid',
    route: mockBusRoutes[0],
    departureDate: futureDate(3),
    pickupPoint: 'Mohakhali',
    selectedSeats: ['A3', 'A4'],
    totalAmount: 1550,
    contactName: 'Test User',
    contactMobile: '01234567890',
  },
  {
    pnr: 'SY654321',
    status: 'Booked',
    route: mockBusRoutes[1],
    departureDate: futureDate(7),
    pickupPoint: 'Arambagh',
    selectedSeats: ['C1'],
    totalAmount: 1200,
    contactName: 'Test User',
    contactMobile: '01234567890',
  },
  {
    pnr: 'SY987654',
    status: 'Canceled',
    route: mockBusRoutes[2],
    departureDate: '2024-07-25T00:00:00.000Z',
    pickupPoint: 'Dampara',
    selectedSeats: ['B2', 'B3'],
    totalAmount: 2400,
    contactName: 'Test User',
    contactMobile: '01234567890',
  },
    {
    pnr: 'SY246810',
    status: 'Expired',
    route: mockBusRoutes[3],
    departureDate: '2024-08-01T00:00:00.000Z',
    pickupPoint: 'Kadamtali Bus Stand',
    selectedSeats: ['D3'],
    totalAmount: 600,
    contactName: 'Test User',
    contactMobile: '01234567890',
  },
];
