import type { BusRoute } from './types';

export const mockBusRoutes: BusRoute[] = [
  {
    id: '1',
    operator: 'Hanif Enterprise',
    from: 'Dhaka',
    to: 'Chittagong',
    departureTime: '08:00 AM',
    arrivalTime: '04:00 PM',
    duration: '8h',
    price: 750,
    rating: 4.5,
    amenities: ['AC', 'WiFi', 'Charging Port'],
    seatLayout: {
      rows: [
        ['A1', 'A2', '', 'A3', 'A4'],
        ['B1', 'B2', '', 'B3', 'B4'],
        ['C1', 'C2', '', 'C3', 'C4'],
        ['D1', 'D2', '', 'D3', 'D4'],
        ['E1', 'E2', '', 'E3', 'E4'],
        ['F1', 'F2', '', 'F3', 'F4'],
        ['G1', 'G2', '', 'G3', 'G4'],
        ['H1', 'H2', '', 'H3', 'H4'],
      ],
      booked: ['A2', 'C3', 'C4', 'F1', 'G3'],
    },
    pickupPoints: ['Gabtoli', 'Mohakhali', 'Abdullahpur'],
  },
  {
    id: '2',
    operator: 'Shyamoli NR Travels',
    from: 'Dhaka',
    to: 'Chittagong',
    departureTime: '10:30 PM',
    arrivalTime: '06:30 AM',
    duration: '8h',
    price: 1200,
    rating: 4.8,
    amenities: ['AC', 'WiFi', 'Blanket', 'Water Bottle'],
    seatLayout: {
      rows: [
        ['A1', 'A2', '', 'A3', 'A4'],
        ['B1', 'B2', '', 'B3', 'B4'],
        ['C1', 'C2', '', 'C3', 'C4'],
        ['D1', 'D2', '', 'D3', 'D4'],
        ['E1', 'E2', '', 'E3', 'E4'],
        ['F1', 'F2', '', 'F3', 'F4'],
        ['G1', 'G2', '', 'G3', 'G4'],
        ['H1', 'H2', '', 'H3', 'H4'],
      ],
      booked: ['B1', 'B2', 'D4', 'E2', 'H1', 'H2', 'H4'],
    },
    pickupPoints: ['Kollanpur', 'Arambagh'],
  },
  {
    id: '3',
    operator: 'Green Line Paribahan',
    from: 'Dhaka',
    to: 'Sylhet',
    departureTime: '07:00 AM',
    arrivalTime: '01:00 PM',
    duration: '6h',
    price: 1000,
    rating: 4.7,
    amenities: ['AC', 'WiFi', 'Snacks'],
    seatLayout: {
      rows: [
        ['A1', 'A2', '', 'A3', 'A4'],
        ['B1', 'B2', '', 'B3', 'B4'],
        ['C1', 'C2', '', 'C3', 'C4'],
        ['D1', 'D2', '', 'D3', 'D4'],
        ['E1', 'E2', '', 'E3', 'E4'],
        ['F1', 'F2', '', 'F3', 'F4'],
      ],
      booked: ['A1', 'A4', 'C2', 'D3'],
    },
    pickupPoints: ['Gabtoli', 'Mohakhali'],
  },
  {
    id: '4',
    operator: 'Ena Transport (Pvt) Ltd',
    from: 'Sylhet',
    to: 'Dhaka',
    departureTime: '02:00 PM',
    arrivalTime: '08:30 PM',
    duration: '6h 30m',
    price: 600,
    rating: 4.2,
    amenities: ['AC', 'WiFi'],
    seatLayout: {
      rows: [
        ['A1', 'A2', '', 'A3', 'A4'],
        ['B1', 'B2', '', 'B3', 'B4'],
        ['C1', 'C2', '', 'C3', 'C4'],
        ['D1', 'D2', '', 'D3', 'D4'],
        ['E1', 'E2', '', 'E3', 'E4'],
        ['F1', 'F2', '', 'F3', 'F4'],
        ['G1', 'G2', '', 'G3', 'G4'],
      ],
      booked: ['B3', 'C1', 'C2', 'E4', 'F2', 'G1'],
    },
    pickupPoints: ['Kadamtali Bus Stand', 'Sobhani Ghat'],
  },
  {
    id: '5',
    operator: 'Shohagh Paribahan',
    from: 'Dhaka',
    to: 'Khulna',
    departureTime: '09:00 PM',
    arrivalTime: '05:00 AM',
    duration: '8h',
    price: 800,
    rating: 4.4,
    amenities: ['AC', 'WiFi', 'Water Bottle'],
    seatLayout: {
      rows: [
        ['A1', 'A2', '', 'A3', 'A4'],
        ['B1', 'B2', '', 'B3', 'B4'],
        ['C1', 'C2', '', 'C3', 'C4'],
        ['D1', 'D2', '', 'D3', 'D4'],
        ['E1', 'E2', '', 'E3', 'E4'],
        ['F1', 'F2', '', 'F3', 'F4'],
        ['G1', 'G2', '', 'G3', 'G4'],
        ['H1', 'H2', '', 'H3', 'H4'],
      ],
      booked: ['A3', 'B1', 'D2', 'D3', 'E1', 'G4', 'H2'],
    },
    pickupPoints: ['Gabtoli', 'Savar'],
  },
];
